name = "simple-a"
license = "MIT"
licenselink = ""
description = "Minimalistic Hugo theme"
min_version = 0.57

tags = ["HannahEscandon", ]
features = ["blog", ]

[author]
    name = "HannahEscandon"
    homepage = ""
<<<<<<< HEAD
    source_repo = ""
=======
    source_repo = "https://github.com/philescandon/simplea"
>>>>>>> f870613fd57e5385f067cddc176a96b5c31d22e2
