name = "simple-a"
license = "MIT"
licenselink = "https://github.com/AlexFinn/simple-a/blob/master/LICENSE.md"
description = "Minimalistic Hugo theme"
min_version = 0.57

tags = ["HannahEscandon", ]
features = ["blog", ]

[author]
    name = "HannahEscandon"
    homepage = ""
    source_repo = "https://github.com/philescandon/simplea"
