name = "simple-a"
license = "MIT"
licenselink = ""
description = "Minimalistic Hugo theme"
min_version = 0.57

tags = ["HannahEscandon", ]
features = ["blog", ]

[author]
    name = "HannahEscandon"
    homepage = ""
    source_repo = ""
